services:
  backend:
    build:
      context: .
    image: jessicalin1205/my-app:latest
    environment:
      - NODE_ENV=development
      - DATABASE_DB=${database}
      - DATABASE_USER=${user}
      - DATABASE_PASSWORD=${password}
      - DATABASE_HOST=${host}

    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

  db:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql:/etc/mysql/mysql.cnf
    environment:
      - DATABASE_DB=${database}
      - DATABASE_USER=${user}
      - DATABASE_PASSWORD=${password}

    ports:
      - ${db_port}:3306
volumes:
  db-data:
